"""0021

Revision ID: 0021
Revises: 0020
Create Date: 2025-08-12 08:25:43.488964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0021'
down_revision: Union[str, None] = '0020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_chart_app_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cluster_id', sa.String(length=256), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('chart_id', sa.Integer(), nullable=True),
    sa.Column('chart_name', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.Column('status_msg', mysql.LONGTEXT(), nullable=True),
    sa.Column('namespace', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('repo_name', sa.String(length=128), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=128), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('tag_name', sa.String(length=256), nullable=True),
    sa.Column('values', mysql.LONGTEXT(), nullable=True),
    sa.Column('extra', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_chart_app_info_id'), 'ops_chart_app_info', ['id'], unique=False)
    op.create_table('ops_chart_repo_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('except_cluster', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.Column('status_msg', mysql.LONGTEXT(), nullable=True),
    sa.Column('cluster_id', sa.String(length=256), nullable=True),
    sa.Column('extra', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_chart_repo_info_id'), 'ops_chart_repo_info', ['id'], unique=False)
    op.create_table('ops_chart_tag_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('chinese_name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('extra', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_chart_tag_info_id'), 'ops_chart_tag_info', ['id'], unique=False)
    op.create_table('ops_chart_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('prefix_name', sa.String(length=128), nullable=True),
    sa.Column('cluster_id', sa.String(length=256), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repo_name', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('latest_version', sa.String(length=128), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('tag_name', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.Column('create_time', sa.String(length=256), nullable=True),
    sa.Column('deprecated', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('chart_content', mysql.LONGTEXT(), nullable=True),
    sa.Column('values_content', mysql.LONGTEXT(), nullable=True),
    sa.Column('readme_content', mysql.LONGTEXT(), nullable=True),
    sa.Column('extra', mysql.LONGTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['ops_chart_repo_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_chart_info_id'), 'ops_chart_info', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ops_chart_info_id'), table_name='ops_chart_info')
    op.drop_table('ops_chart_info')
    op.drop_index(op.f('ix_ops_chart_tag_info_id'), table_name='ops_chart_tag_info')
    op.drop_table('ops_chart_tag_info')
    op.drop_index(op.f('ix_ops_chart_repo_info_id'), table_name='ops_chart_repo_info')
    op.drop_table('ops_chart_repo_info')
    op.drop_index(op.f('ix_ops_chart_app_info_id'), table_name='ops_chart_app_info')
    op.drop_table('ops_chart_app_info')
    # ### end Alembic commands ###
