"""0023

Revision ID: 0023
Revises: 0022
Create Date: 2025-08-12 08:25:43.488964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0023'
down_revision: Union[str, None] = '0022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_sshkey_info',
    sa.Column("id", sa.String(length=256), primary_key=True, nullable=False, index=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('project_id', sa.String(length=256), nullable=True),
    sa.Column('project_name', sa.String(length=256), nullable=True),
    sa.Column('account_id', sa.String(length=256), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('status_msg', mysql.LONGTEXT(), nullable=True),
    sa.Column('key_content', mysql.LONGTEXT(), nullable=True),
    sa.Column('namespace', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('user_name', sa.String(length=128), nullable=True),
    sa.Column('configmap_name', sa.String(length=128), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('extra', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ops_chart_app_info_id'), table_name='ops_chart_app_info')
    op.drop_table('ops_chart_app_info')
    # ### end Alembic commands ###
