"""

Revision ID: 0007
Revises: 0006
Create Date: 2025-05-08 08:14:59.747729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_instance_info',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('cluster_id', sa.String(length=128), nullable=True),
    sa.Column('cluster_name', sa.String(length=128), nullable=True),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('server_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('openstack_id', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=128), nullable=False),
    sa.Column('operation_system', sa.String(length=128), nullable=False),
    sa.Column('floating_ip', sa.String(length=128), nullable=True),
    sa.Column('security_group', sa.String(length=128), nullable=True),
    sa.Column('flavor_id', sa.String(length=128), nullable=True),
    sa.Column('image_id', sa.String(length=128), nullable=True),
    sa.Column('network_id', sa.String(length=128), nullable=True),
    sa.Column('subnet_id', sa.String(length=128), nullable=True),
    sa.Column('sshkey_name', sa.String(length=128), nullable=True),
    sa.Column('node_type', sa.String(length=128), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=128), nullable=False),
    sa.Column('user', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('cpu', sa.Integer(), nullable=True),
    sa.Column('gpu', sa.Integer(), nullable=True),
    sa.Column('mem', sa.Integer(), nullable=True),
    sa.Column('disk', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('extra', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_instance_info_id'), 'ops_instance_info', ['id'], unique=False)
    op.create_table('ops_node_info',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('cluster_id', sa.String(length=128), nullable=False),
    sa.Column('cluster_name', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('openstack_id', sa.String(length=128), nullable=True),
    sa.Column('server_id', sa.String(length=128), nullable=True),
    sa.Column('instance_id', sa.String(length=128), nullable=True),
    sa.Column('admin_address', sa.String(length=128), nullable=False),
    sa.Column('bus_address', sa.String(length=128), nullable=False),
    sa.Column('floating_ip', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=128), nullable=False),
    sa.Column('node_type', sa.String(length=128), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=128), nullable=False),
    sa.Column('flavor_id', sa.String(length=128), nullable=True),
    sa.Column('security_group', sa.String(length=128), nullable=True),
    sa.Column('private_key', sa.Text(), nullable=True),
    sa.Column('auth_type', sa.String(length=128), nullable=True),
    sa.Column('user', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('extra', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_node_info_id'), 'ops_node_info', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ops_node_info_id'), table_name='ops_node_info')
    op.drop_table('ops_node_info')
    op.drop_index(op.f('ix_ops_instance_info_id'), table_name='ops_instance_info')
    op.drop_table('ops_instance_info')
    # ### end Alembic commands ###
